### ISSUE TITLE
dbus: new alert notification always "yellow"

### ISSUE THREAD

**Issue by dperpeet** [fedora-selinux/setroubleshoot#12]
I think this is currently hardcoded in [setroubleshoot/server.py#L116](https://github.com/fedora-selinux/setroubleshoot/blob/8f19f77f880bf741d60e0a3ae037727a755360b9/framework/src/setroubleshoot/server.py#L116)
Besides making this info available in the details as well, I think this should be fixed to reflect the level of the alert.

**Comment by bachradsusi** [comment]
yellow level is considered to be default however the code doesn't really look right. I'll prepare a fix for it. Thanks for the report.

**Comment by bachradsusi** [comment]
How to generate a green alert:

    # chcon -t admin_home_t /etc/ssh/ssh_host_ecdsa_key
    # systemctl restart sshd

You need to restore the label back when you are finished:

    # restorecon -R -v /etc/ssh

**Comment by bachradsusi** [comment]
`setroubleshoot-3.3.5-0.1` builds with the fix will be available for f23, f24 and rawhide  in https://copr.fedorainfracloud.org/coprs/plautrba/setroubleshoot/ soon

**Comment by mgrepl** [comment]
It works as expected. I am able to see

string "green"

Great.

Looking forward to see it in Cockpit.

**Comment by bachradsusi** [comment]
Fixed by https://github.com/fedora-selinux/setroubleshoot/commit/5f5dc8f846fd428bdd20d4b09d2bfaecf6b76c64
