### ISSUE TITLE
setroubleshoot-server dependencies

### ISSUE THREAD

**Issue by dperpeet** [fedora-selinux/setroubleshoot#17]
When installing `setroubleshoot-server` on fedora 23, it also pulls in the dependency `python3-cairo`. I think this is a graphical library - is it necessary for the server?

**Comment by bachradsusi** [comment]
As setroubleshoot was originally written as a desktop application it uses GObject so that it requires `python3-gobject` which requires `python3-cairo`.

**Comment by dperpeet** [comment]
Thanks for the answer!
Closing this for now, as this is rather a long term design question, not an issue with the current code.
