### ISSUE TITLE
dbus: solutions should be weighted

### ISSUE THREAD

**Issue by dperpeet** [fedora-selinux/setroubleshoot#22]
The possible solutions for an alert should be weighted somehow.

As an easy option, they could be ordered from most to least recommended or something similar.

Would another piece of information, e.g. "recommended" or "not recommended" help? I think while possible, it might not be a good thing since it might lead to an overabundance of information for the user.

**Comment by bachradsusi** [comment]
setroubleshoot-3.3.5-0.2 builds with the priority patch will be soon in https://copr.fedorainfracloud.org/coprs/plautrba/setroubleshoot/

**Comment by bachradsusi** [comment]
Fixed by https://github.com/fedora-selinux/setroubleshoot/commit/42edc1dcae82da6dd79f4437631eb0f0ebb11bbd
