### ISSUE TITLE
dbus: ignore alerts

### ISSUE THREAD

**Issue by dperpeet** [fedora-selinux/setroubleshoot#24]
It would be nice to interact with the ignore feature of sealert:
- ignore a specific type of alert ("known issues")
- view list of ignored alerts and optionally "unignore" an item

**Comment by bachradsusi** [comment]
Example:

    $ dbus-send --system --print-reply --dest=org.fedoraproject.Setroubleshootd /org/fedoraproject/Setroubleshootd org.fedoraproject.SetroubleshootdIface.set_filter string:bff0a5ea-ebbf-4038-bf34-f150c1d7b2bc string:always
    method return time=1462392596.121002 sender=:1.217 -> destination=:1.221 serial=7 reply_serial=2
      boolean true

    $ dbus-send --system --print-reply --dest=org.fedoraproject.Setroubleshootd /org/fedoraproject/Setroubleshootd org.fedoraproject.SetroubleshootdIface.get_all_alerts_ignored
    method return time=1462392601.797407 sender=:1.217 -> destination=:1.222 serial=9 reply_serial=2
    array [
      struct {
         string "bff0a5ea-ebbf-4038-bf34-f150c1d7b2bc"
         string "SELinux is preventing python3 from using the dyntransition access on a process."
         int32 1
      }
      struct {
         string "2118b549-3015-4ab8-bf23-a24bef3cd037"
         string "SELinux is preventing httpd from read access on the file test-avc.conf."
         int32 1
      }

**Comment by bachradsusi** [comment]
setroubleshoot COPR build with the new API - https://copr.fedorainfracloud.org/coprs/plautrba/setroubleshoot/build/183303/

**Comment by bachradsusi** [comment]
And https://github.com/fedora-selinux/setroubleshoot/commit/ee06a8f48e865d8617f5a60500a968f60ca9e8fe

Fixed in setroubleshoot-3.3.7
