### ISSUE TITLE
don't use a status icon when the notification server supports persistence

### ISSUE THREAD

**Issue by bachradsusi** [fedora-selinux/setroubleshoot#50]
Reported by mccann at https://fedorahosted.org/setroubleshoot/ticket/10

Newer notifications servers (gnome-shell, or notification-daemon >= 0.6.0) support persistence of notifications. This means that a bubble won't just disappear after it is shown - it will stay until it is seen/addressed/acted upon. This means we don't have to rely on a status icon to provide the persistence for the message. In fact we should remove the status icons since they will provide a confusing duplication of this information.

On top of that, GNOME 3 won't really be supporting status icons at all. So this works out nicely.

You can query the server for support of the "persistence" capability like so: ​http://git.gnome.org/browse/libnotify/tree/tests/test-persistence.c

You'll need libnotify >= 0.6.1 too.

See ​http://live.gnome.org/GnomeShell/Design/Guidelines/MessageTray/Compatibility

**Comment by bachradsusi** [comment]
See also https://pagure.io/setroubleshoot/issue/8

**Comment by csoriano89** [comment]
Hey!

Just a heads up, it would be helpful to see this happening soon since GNOME Shell won't have a default way to show status icons for 3.26, planned for Fedora 27.

Feel free to contact me if you need any help or have any question.

**Comment by bachradsusi** [comment]
I started rewrite of seapplet to Python 3 and to use Gnome 3 notifications in https://pagure.io/fork/plautrba/setroubleshoot/commits/WIP-gnome3-notifications

Builds are available 

https://copr.fedorainfracloud.org/coprs/plautrba/setroubleshoot/
