### ISSUE TITLE
create a plugin which analyzes execmem denials

### ISSUE THREAD

**Issue by milosmalik** [fedora-selinux/setroubleshoot#55]
Description of problem:
* there are setroubleshoot plugins which are able to analyze execheap, execmod and execstack AVCs, but there is no plugin which would be able to correctly analyze execmem AVCs and which would provide a relevant advice
* selinux-policy brings several booleans related to execmem AVCs:
boinc_execmem,cluster_use_execmem,cups_execmem,deny_execmem,glance_use_execmem,httpd_execmem,virt_use_execmem,xserver_execmem
* https://www.akkadia.org/drepper/selinux-mem.html

**Comment by vmojzis** [comment]
https://github.com/fedora-selinux/setroubleshoot/pull/87
