### ISSUE TITLE
Translations are incomplete

### ISSUE THREAD

**Issue by AsciiWolf** [fedora-selinux/setroubleshoot#63]
Some strings are not translated even though they seem to be fully translated in Zanata, other strings are completely missing in both the Zanata and the po files. Please, consider updating the pofiles.

![setroubleshoot](https://user-images.githubusercontent.com/2339930/29250343-417fd9c4-8041-11e7-91cb-72c5d5340949.png)

**Comment by bachradsusi** [comment]
Thanks for the report!

pot files were updated in https://fedora.zanata.org/iteration/view/setroubleshoot/master?dswid=-5156

At the same time, I hope I fixed the problem with untranslated labels used in browser.glade

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by AsciiWolf** [comment]
@bachradsusi Would it be possible to update the translations one more time? I have fixed some wrongly translated strings in the Czech translation. Thanks!

**Comment by bachradsusi** [comment]
Sure. And I'll update translations again just before the next release.

**Comment by bachradsusi** [comment]
#: ../src/setroubleshoot/signature.py:215
     msgid "capability2"
    -msgstr ""
    +msgstr "schopnost2"

capability2 is the name of SELinux class. It shouldn't be translated. I'll fix it in the code.

**Comment by AsciiWolf** [comment]
Oops, thanks for notifying me! What about the "capability" string? It's also translated...

**Comment by bachradsusi** [comment]
I might be wrong since all other classes are translated - https://github.com/fedora-selinux/setroubleshoot/blob/master/framework/po/cs.po#L446

But while directory - adresar is quite clear, capability2 - schopnost2 sounds strange to me, but I can live with it. And de.po translates classes as well.
