### ISSUE TITLE
Add SysVInit (OpenRC) Support

### ISSUE THREAD

**Issue by Heavenser** [fedora-selinux/setroubleshoot#70]
I use Gentoo Linux with OpenRC, and I install setroubleshoot from source, when I execute setroubleshootd command, it prompt me missing systemd module.

**Comment by bachradsusi** [comment]
Could you please share the traceback? I guess it's related to

    framework/src/setroubleshoot/server.py:44  import systemd.journal

**Comment by Heavenser** [comment]
OK. This is the traceback:

Traceback (most recent call last):
  File "/usr/sbin/setroubleshootd", line 104, in <module>
    from setroubleshoot.server import RunFaultServer
  File "/usr/lib64/python3.6/site-packages/setroubleshoot/server.py", line 44, in <module>
    import systemd.journal
ModuleNotFoundError: No module named 'systemd'
